### PR TITLE
Improved typing for insert and replace

### PR DESCRIPTION
**Pull request by Cooke**
Should always be partial of T right?

### CODE REVIEW

**Comment by charsleysa** [comment]
@Cooke insert and replace are a little bit more complicated in what they accept.

If you take a look at the tests you'll see the variety of arguments they accept.

**Comment by Cooke** [comment]
> @Cooke insert and replace are a little bit more complicated in what they accept.
> 
> If you take a look at the tests you'll see the variety of arguments they accept.

Why is all tests passing locally?

**Comment by charsleysa** [comment]
@Cooke not sure, can you please verify that when you run `npm test` that all the tests are executing? (Please post results of tests here)

**Comment by Cooke** [comment]
> @Cooke not sure, can you please verify that when you run `npm test` that all the tests are executing? (Please post results of tests here)

There is some weird caching going on. I have to manually go in and touch each of the test files for them pick up my changes in the lib. 

The library seems to accept insert/replace where the input object property name is equal to the column name (not the "table types" property name) which seems hard to overcome. I give up. 

This is by far the best TS supported query library (with models) for node I have yet found. I would by nice to make it even more strict.

**Comment by charsleysa** [comment]
@Cooke I feel your pain.

Getting the typings right isn't an easy task when the functions accept a variety of different inputs. 

We have been using in production but always have to be careful with our naming when using insert, replace, etc. 

I'll leave this PR open incase you manage to solve it in the future.

**Comment by charsleysa** [comment]
@Cooke closing this as v3.0.1 adds typings that I think covers this.

**Pull request closed without merging**
